name: Generate Sketch Library

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.0
      - name: Install dependencies
        run: yarn install
      - name: Generate Sketch Library
        run: yarn start
      - uses: actions/upload-artifact@v2
        with:
          name: Material Design Icons - Sketch Library
          path: material-design-icons.sketch
